from .random_agent import RandomAgent
from .attelia2_agent import Attelia2Agent
from .q_learning_agent import QLearningAgent
from .q_learning_replay_agent import QLearningPrioritizedReplayAgent
from .debug_agent import DebugAgent
from .silent_agent import SilentAgent
from .tf_dqn_agent import TensorForceDQNAgent
from .coach_a3c_agent import CoachA3CAgent
from .coach_a3c_p_ignore_agent import CoachA3CPunishIgnoreAgent
from .classification_agent import ClassificationAgent
