# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-08 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurture', '0007_exceptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='learning_agent',
            field=models.IntegerField(choices=[(0, 'Random')], default=0),
            preserve_default=False,
        ),
    ]
