# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-19 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurture', '0012_auto_20180718_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='reward_state_message',
            field=models.TextField(),
        ),
    ]
