# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurture', '0017_auto_20180816_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='hit_cap',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
