# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurture', '0019_auto_20180827_0952'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='actionlog',
            index_together=set([('user', 'query_time')]),
        ),
    ]
